### ISSUE TITLE
Use API call to get region name

### ISSUE THREAD

**Issue by outscale-mgo** [outscale-dev/osc-tui#11]
https://github.com/outscale-dev/osc-tui/blob/93a44e35a523791494dc5c711042f91a08737f87/src/popup.py#L54

This line have 3 problems:

1. it refer to regions that doesn't exist anymore
2. it doesn't contain all regions
3. it's not future proof

If we used the api call ReadRegions we could simply get the region list, and use that instead.

**Comment by outscale-fne** [comment]
@Pierre570 tu prends?

**Comment by Pierre570** [comment]
Yes mais pour le moment on peut pas utiliser ReadRegions
