### ISSUE TITLE
Feature request: doing a search on any screen with key '/' or '?'

### ISSUE THREAD

**Issue by Soulou** [outscale-dev/osc-tui#75]
When browsing resources, it would be great to do a search as we can do on the web cockpit using the slash or interrogation tag character, it would improve usability a lot (which is currently a bit limited for our usage)

Thanks a lot

**Comment by outscale-mgo** [comment]
Yes, this was in our TODO list since some time.
I'm currently working on this issue, should be solve soon (I hope next week)
